config/routes.rb
XExam::Application.routes.draw do
  resources :examinations

  resources :answers

  resources :questions

  resources :subjects do
    member do 
      get 'start'
    end
  end

  devise_for :users

  resources :users
  root :to => "home#index"

  Dir.glob File.expand_path("plugins/*", Rails.root) do |plugin_dir|
    file = File.join(plugin_dir, "config/routes.rb")
    if File.exists?(file)
      begin
        instance_eval File.read(file)
      rescue Exception => e
        puts "An error occurred while loading the routes definition of #{File.basename(plugin_dir)} plugin (#{file}): #{e.message}."
        exit 1
      end
    end
  end  
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  # attr_accessible :title, :body

  scope :for_user, lambda { |user| where("user_id = ?", user.id)}
end

app/models/exam_answer.rb
class ExamAnswer < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/question.rb
class Question < ActiveRecord::Base
  # attr_accessible :title, :body

  scope :sections, lambda {|sections| where("section in (?)", sections) }
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/subject_item.rb
class SubjectItem < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!
	
	def index 
		@subjects = Subject.all
		@exams = Exam.for_user(current_user)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	before_filter :authenticate_user!
	
	def start
		@subject = Subject.find(params[:id])
		generate_subject_papar(@subject)
		# @subject.
	end

	private 
	def generate_subject_papar(subject)
		render :template => "subjects/_template"
		# subject.tempate
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def index
		@users = User.all
	end

	def show 
		@user = User.find(params[:id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/questions_helper.rb
require 'x-exam/builder'

module QuestionsHelper

	class QuestionBuilider

	end

	# question_samples(number, sections..., options)
	#   number: Integer 取出几个样例
	#   sections: Array 节数组
	#   options: Hash 配置选项
	#
	# SAMPLES
	#   <h2>选择题</h2>
	#   <% question_samples(20, "linux 基础知识选择题") do |question| %>
	def question_samples(number, *args, &block)

		options = args.extract_options! || {}

		questions = Question.sections(args).sample(number)

		questions.each_with_index do |quest, i|
			builder = build_question(quest, i)
			builder.render(&block)
		end

		nil
	end

	def build_question(quest, index )
		builder   = case quest.quest_type
					when "single_choice", "multiple_choice", "fill_blank", "programming_simulation"
						name = "quest_#{quest.id}"
						ctnt = YAML.load(quest.content)
						ctnt["point"] = quest.point
						ctnt["index"] = index
						klass = "XExam::Builder::#{quest.quest_type.classify}". constantize
						klass.new(name, ctnt, self)
					else
						plugin = load_plugins(quest.quest_type)
					end

	end

	def load_plugins(type)

	end

	def question(name)
	end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/home/index.html.erb
<% unless @exams.blank? %>
<ul class='unstyled'>
	<% @exams.each do |exam| %>
		<li><%= link_to exam.create_at, exam %></li>
	<% end %>
</ul>
<% end %>

<% unless @subjects.blank? %>
<ul class='unstyled'>
	<% @subjects.each do |subject| %>
	<li>
		<%= subject.name %> 
		<%= link_to '开始', start_subject_path(subject), :class => 'btn btn-primary' %>
	</li>
	<% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XExam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body onload="sh_highlightDocument('assets/lang/', '.js');">
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class='container'>
    	<%= yield %>
    </div>

    <script type="text/javascript">
      load_code_mirror();
    </script>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/subjects/_template.html.erb
<h2>单选择题</h2>
<%# question_samples(4, "基础选择题" ) do |q| %>
	<h4><%#= q.question %> ( <%#= q.point %> 分 )</h4>
	<%# q.answers.each do |key,value| -%>
		<%#= q.render_answer(key, value) %>
	<%# end %>
	<br>
<%# end %>

<h2>单选择题</h2>
<%= question_samples(4, "基础选择题" ) %>

<h2>多选择题</h2>
<%= question_samples(3, "基础多选题" ) %>

<h2>填空</h2>
<%= question_samples(2, "基础填空题" ) %>

<h2>模拟题</h2>
<%= question_samples(1, "程序题") %>